databases:
  - name: backend_portfolio
    databaseName: backend_portfolio
    user: backend_portfolio

services:
  - type: web
    name: backend_portfolio
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backend_portfolio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false